direction: right

Long-lived {
    style.stroke: blue
    style.bold: true
    
    Weight A: 0 - 20
    Weight B: 0 - 20
    Weight C: 0 - 20
}

Short-lived {
    style.stroke: orange
    
    Activation 1: 1 - 3
    Temp 1: 2 - 4
    Activation 2: 5 - 7
    Workspace 1: 6 - 8
    Activation 3: 10 - 12
    Temp 2: 11 - 13
}

Long-lived -> Short-lived {
    style.stroke-dash: 4
}
