direction: down

Pool: Weight Pool {
    style.stroke: blue
    style.bold: true
    
    S1: 256KB cached blocks
    S2: 512KB cached blocks
    S3: 1MB cached blocks
}

MA: Model A weight
MB: Model B weight
MC: Model C weight
MD: Model D weight

MA -> Pool.S1: 256KB
MB -> Pool.S1: 256KB
MC -> Pool.S3: 1MB
MD -> Pool.S3: 1MB
