direction: right

A: Raw Text
B: Tokenizer / BPE
C: Token
D: Token ID {
  style: {
    stroke-dash: 5
  }
}
E: One-hot {
  style: {
    stroke-dash: 5
  }
}
F: Embedding Lookup
G: Dense Vector
H: RNN / Transformer

A -> B
B -> C
C -> D
D -> E
E -> F
F -> G
G -> H
