direction: right

fc: "Fully Connected" {
  style.stroke: "#dc2626"
  style.stroke-width: 2
  style.bold: true

  grid-rows: 3
  grid-columns: 3
  style.stroke: "#dc2626"

  i1: "input 1"
  i2: "input 2"
  i3: "input 3"
  i4: "input 4"
  i5: "input 5"
  i6: "input 6"
  o1: "output 1"
  o2: "output 2"
  o3: "output 3"
}

fc.i1 -> fc.o1
fc.i1 -> fc.o2
fc.i1 -> fc.o3
fc.i2 -> fc.o1
fc.i2 -> fc.o2
fc.i2 -> fc.o3
fc.i3 -> fc.o1
fc.i3 -> fc.o2
fc.i3 -> fc.o3
fc.i4 -> fc.o1
fc.i4 -> fc.o2
fc.i4 -> fc.o3
fc.i5 -> fc.o1
fc.i5 -> fc.o2
fc.i5 -> fc.o3
fc.i6 -> fc.o1
fc.i6 -> fc.o2
fc.i6 -> fc.o3

local: "Local Connectivity" {
  style.stroke: "#2563eb"
  style.stroke-width: 2
  style.bold: true

  grid-rows: 3
  grid-columns: 3

  i1: "input 1"
  i2: "input 2"
  i3: "input 3"
  i4: "input 4"
  i5: "input 5"
  i6: "input 6"
  o1: "output 1"
  o2: "output 2"
  o3: "output 3"
}

local.i1 -> local.o1
local.i2 -> local.o1
local.i3 -> local.o1
local.i3 -> local.o2
local.i4 -> local.o2
local.i5 -> local.o2
local.i5 -> local.o3
local.i6 -> local.o3
local.i4 -> local.o3

fc -> local: "" {style.stroke-dash: 5; style.opacity: 0}
