direction: right

Dockerfile: {
  style: {
    stroke: blue
    stroke-width: 3
    bold: true
  }
}
Image 1: Image {
  style: {
    stroke: green
  }
}
Registry: {
  style: {
    stroke: green
  }
}
Image 2: Image {
  style: {
    stroke: green
  }
}
Container: {
  style: {
    stroke: blue
    stroke-width: 3
    bold: true
  }
}

Dockerfile -> Image 1: docker build
Image 1 -> Registry: docker push
Registry -> Image 2: docker pull
Image 2 -> Container: docker run
