direction: right

Forward {
  F1: Forward L1
  F2: Forward L2
  F3: Forward L3
  F4: Forward L4
  
  F1 -> F2 -> F3 -> F4
}

Backward {
  B4: Backward L4
  B3: Backward L3
  B2: Backward L2
  B1: Backward L1
  
  B4 -> B3 -> B2 -> B1
}

Forward.F4 -> Backward.B4 {
  style.stroke-dash: 4
}
Forward.F1 -> Backward.B1: Save Activation {
  style.stroke-dash: 4
  style.stroke: green
}
Forward.F2 -> Backward.B2: Save Activation {
  style.stroke-dash: 4
  style.stroke: green
}
Forward.F3 -> Backward.B3: Save Activation {
  style.stroke-dash: 4
  style.stroke: green
}
