direction: down

PM: Parameter Memory
SF: Static Footprint
PersM: Persistent Memory
RWS: "+ Runtime Working Set"
PLM: Peak Live Memory {
    style.bold: true
    style.stroke-width: 3
}
AR: Allocator / Runtime
PF: Physical GPU Footprint {
    style.bold: true
    style.stroke-width: 3
    style.stroke: orange
}

PM -> SF
SF -> PersM
PersM -> RWS
RWS -> PLM
PLM -> AR
AR -> PF
