direction: right

A: Corpus {
  style.stroke: green
  style.stroke-width: 3
}

B: Pre-tokenization {
  style.stroke: blue
}

C: Byte sequences {
  style.stroke: blue
}

D: Count adjacent pairs {
  style.stroke: blue
}

E: Choose best pair {
  style.stroke: orange
  style.stroke-width: 3
}

F: Merge {
  style.stroke: blue
}

A -> B
B -> C
C -> D
D -> E
E -> F
F -> D
