direction: right

A: Raw Text {
  style.stroke: green
}
B: Tokenizer {
  style.stroke: orange
  style.stroke-width: 3
}
C: Token IDs {
  style.stroke: green
}
D: Embedding {
  style.stroke: blue
}
E: Transformer {
  style.stroke: blue
}
F: Logits {
  style.stroke: green
}

A -> B
B -> C
C -> D
D -> E
E -> F
