direction: down

stage1: {
  label: ""
  direction: right
  h0: h_0 {
    shape: circle
  }
  h1: h_1 {
    shape: circle
  }
  h2: h_2 {
    shape: circle
  }
  h0 -> h1: J_1
  h1 -> h2: J_2
}

stage2: {
  label: ""
  direction: right
  dots: "..." {
    shape: circle
    style.stroke: transparent
    style.fill: transparent
  }
  hT: h_T {
    shape: circle
  }
  dots -> hT: J_T
}

stage1.h2 -> stage2.dots: J_3
