direction: right

a: "A\nposition 1" {
  style.stroke: "#16a34a"
  style.bold: true
}
b: "B\nposition 2" {
  style.stroke: "#16a34a"
  style.bold: true
}
c: "C\nposition 3" {
  style.stroke: "#16a34a"
  style.bold: true
}
d: "D\nposition 4" {
  style.stroke: "#16a34a"
  style.bold: true
}

a -- b
b -- c
c -- d
