layout-engine: elk
direction: down

classes: {
  node: { style.font-size: 32 }
}

x: { shape: circle; class: node; style: { stroke: "#aaaaaa"; bold: true } }

Weight layer 1: { shape: rectangle; class: node; style: { stroke: "#4a90e2"; bold: true } }
ReLU: { shape: oval; class: node; style: { stroke: "#f5a623"; bold: true } }
Weight layer 2: { shape: rectangle; class: node; style: { stroke: "#4a90e2"; bold: true } }

Plus: { shape: circle; label: "+"; class: node; style: { stroke: "#e32a4a"; bold: true } }
Output ReLU: { shape: oval; label: "ReLU"; class: node; style: { stroke: "#f5a623"; bold: true } }

x -> Weight layer 1
Weight layer 1 -> ReLU
ReLU -> Weight layer 2
Weight layer 2 -> Plus: "F(x)" { style.font-size: 32 }

x -> Plus: "Identity (x)" { style: { stroke: "#e32a4a"; stroke-dash: 5 }; style.font-size: 32 }

Plus -> Output ReLU: "F(x) + x" { style.font-size: 32 }
