direction: down

LargeM: "M 很大：tile 多" {
  T1: tile
  T2: tile
  T3: tile
  T4: tile
  T5: tile
  T6: tile
  T7: tile
  T8: tile
  T1 -- T2 -- T3 -- T4
  T5 -- T6 -- T7 -- T8
}

SmallM: "M 很小：tile 少" {
  S1: tile
  S2: tile
  S1 -- S2
}

Fill_Node: "容易填满 SM" {
  style.stroke: green
}
Idle: "大量 SM 空闲" {
  style.stroke: red
}

LargeM -> Fill_Node
SmallM -> Idle
