direction: right

Storage: { style.stroke: green }
Remote Reader: { style.stroke: blue }
Memory Cache: { style.stroke: blue }
Trainer: {
  style.stroke: blue
  style.bold: true
}

Storage -> Remote Reader
Remote Reader -> Memory Cache
Memory Cache -> Trainer
