direction: right

Storage: { style.stroke: green }
Remote Reader: { style.stroke: blue }
Host Memory: { style.stroke: orange }
GPU Memory: { style.stroke: red }

Storage -> Remote Reader -> Host Memory -> GPU Memory
