direction: right

Storage: {
  style.stroke: green
}

Worker1: { style.stroke: blue }
Worker2: { style.stroke: blue }
Worker3: { style.stroke: blue }
Worker4: { style.stroke: blue }

Prefetch Queue: { style.stroke: blue }
GPU: {
  style.stroke: blue
  style.bold: true
  style.stroke-width: 3
}

Worker1 -> Storage
Worker2 -> Storage
Worker3 -> Storage
Worker4 -> Storage

Worker1 -> Prefetch Queue
Worker2 -> Prefetch Queue
Worker3 -> Prefetch Queue
Worker4 -> Prefetch Queue

Prefetch Queue -> GPU
