direction: down

Remote Storage: {
  style.stroke: green
}
Persistent Data Service: {
  style.stroke: blue
  style.bold: true
  style.stroke-width: 3
}
Training JobA: { style.stroke: blue }
Training JobB: { style.stroke: blue }
Training JobC: { style.stroke: blue }

Remote Storage -> Persistent Data Service: 首次读取
Persistent Data Service -> Training JobA
Persistent Data Service -> Training JobB
Persistent Data Service -> Training JobC
