shape: sequence_diagram

RemoteDataWorker: { style.stroke: blue }
TrainerBuffer: { style.stroke: blue }
GPU: {
  style.stroke: blue
  style.bold: true
}

RemoteDataWorker -> TrainerBuffer: Prepare BatchN
TrainerBuffer -> GPU: Deliver BatchN

GPU -> GPU: ForwardBackward
RemoteDataWorker -> TrainerBuffer: BatchN+1
RemoteDataWorker -> TrainerBuffer: BatchN+2
