direction: down

Distributed Storage: {
  style.stroke: green
}

Remote Reader1: { style.stroke: blue }
Remote Reader2: { style.stroke: blue }
Remote Reader3: { style.stroke: blue }
Remote Reader4: { style.stroke: blue }

Trainer Prefetch Buffer: { style.stroke: blue }
GPU Trainer: {
  style.stroke: blue
  style.bold: true
  style.stroke-width: 3
}

Distributed Storage -> Remote Reader1
Distributed Storage -> Remote Reader2
Distributed Storage -> Remote Reader3
Distributed Storage -> Remote Reader4

Remote Reader1 -> Trainer Prefetch Buffer
Remote Reader2 -> Trainer Prefetch Buffer
Remote Reader3 -> Trainer Prefetch Buffer
Remote Reader4 -> Trainer Prefetch Buffer

Trainer Prefetch Buffer -> GPU Trainer
