direction: down

Distributed Storage: {
  style.stroke: green
}
Storage Client: {
  style.stroke: blue
}
Training Process: {
  style.stroke: blue
}
GPU: {
  style.stroke: blue
  style.bold: true
  style.stroke-width: 3
}

Distributed Storage -> Storage Client
Storage Client -> Training Process
Training Process -> GPU
