direction: right

DS: "Distributed\nStorage" {
  style.stroke: green
}
SC: "Storage\nClient" {
  style.stroke: blue
}
TP: "Training\nProcess" {
  style.stroke: blue
}
GPU: "GPU" {
  style.stroke: blue
  style.bold: true
  style.stroke-width: 3
}

DS -> SC -> TP -> GPU
