direction: right

h0: h₀ {
  style: { stroke: blue; stroke-width: 3; bold: true }
}
h1: h₁ {
  style: { stroke: blue; stroke-width: 3; bold: true }
}
h2: h₂ {
  style: { stroke: blue; stroke-width: 3; bold: true }
}
h3: h₃ {
  style: { stroke: blue; stroke-width: 3; bold: true }
}
h4: h_T {
  style: { stroke: blue; stroke-width: 3; bold: true }
}
x1: x₁
x2: x₂
x3: x₃

h0 -> h1: f_W(h₀, x₁)
h1 -> h2: f_W(h₁, x₂)
h2 -> h3: f_W(h₂, x₃)
h3 -> h4: "..." {
  style: { stroke-dash: 4 }
}

x1 -> h1
x2 -> h2
x3 -> h3
